import NavBar from "../component/Navbar";
import Sidebar from "./component/sidebar";
import SearchHeader from "./component/header";
import Restorentcart from "./component/restorentcart";
import { Metadata } from "next";

export const metadata: Metadata = {
    title: "| search",
    description: "Generated by create next app",
  };
export default function SearchPage() {
    return (
        <>
            <SearchHeader />
            <div className="flex py-4 m-auto w-2/3 justify-between items-start">
                <Sidebar />
                <div className="w-5/6">
                    <Restorentcart />
                </div>
            </div>
        </>
    )
}