import { Metadata } from "next/types";
import HeaderRestorent from "./components/header";




export const metadata: Metadata = {
    title: " | Restorent",
    description: "Generated by create next app",
    keywords: ["rohan", "developer"]
  };

export default function restorentlayout({
    children,
  }: Readonly<{
    children: React.ReactNode;
  }>){    
    return(
        <>
            <HeaderRestorent />
            <div className="flex m-auto w-2/3 justify-between items-start 0 -mt-11">
                {children}
            </div>
        </>
    )
}